name: test

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: npm install pnpm
        run: npm install pnpm -g
      - name: pnpm install
        run: pnpm install
      - name: pnpm build:ui
        run: pnpm build:ui
